### ISSUE TITLE
Black store, community

### ISSUE THREAD

**Issue by CrafterSvK** [Nefelim4ag/steam-wine#3]
Store is black and loading all the time.

**Comment by nefelim4ag** [comment]
@CrafterSvK, AFAIK it's a problem with CEF and Wine, and i don't know how to fix that with steam (on lol wrapper i issue --no-sandboxes to exe file)

**Comment by nefelim4ag** [comment]
That fix: https://github.com/Nefelim4ag/steam-wine/pull/4
